### ISSUE TITLE
jled library question

### ISSUE THREAD

**Issue by JAG1208** [jandelgado/jled#10]
Hello Jan.
Firstly I´ll appreciate your contribution, it is a very useful library!!.
I'm wondering to know if there is any way to start over when use the repeat option.
The idea is to blink the led X times when a button is pressed , then stop, and when the same button is pressed again, blink it X times again
Thanks!!

**Comment by jandelgado** [comment]
Currently not - but I plan to include a `Reset()` method in the next release (scheduled within the next two weeks) allowing exactly this.

**Comment by JAG1208** [comment]
Thanks. I'll wait for it.
