### ISSUE TITLE
times in millis should be 32bit values

### ISSUE THREAD

**Issue by hansimglueck** [jandelgado/jled#109]
My first go with this very nice library is frustrating me right now, because I can have the breath-Effect stay on for just 65 seconds...
Unfortunately my c++-skills dont suffice to change that in the source - I tried but things just didnt work.

**Comment by Welsyntoffie** [comment]
@hansimglueck 
Use below code to run breath forever...
`auto freezetime_sequence = JLed(9).Breathe(4000).Forever();`

**Comment by Welsyntoffie** [comment]
Here is a lot more uses for using this library 
[https://github.com/Welsyntoffie/csgo-gsi-python-to-arduino/tree/develop/arduino/CSGO_lighting_controller](url)
