### ISSUE TITLE
Why is 'MinBrightness' not in red font

### ISSUE THREAD

**Issue by greyczj** [jandelgado/jled#111]
![Snipaste_2023-01-11_14-07-49](https://user-images.githubusercontent.com/31653793/211730315-d9e5e7f8-1dbf-40b1-9ce1-b9255d231123.jpg)
Why is 'MinBrightness' not in red font, and it is not convenient to confirm whether the input is correct

**Comment by jandelgado** [comment]
Thanks for the report. It seems that some of the latest additions are missing in the [keywords.txt](https://github.com/jandelgado/jled/blob/master/keywords.txt) file. I'll add it soon.

**Comment by jandelgado** [comment]
fixed in 4.12.1
