### ISSUE TITLE
Return pin's previous state after Blink is over

### ISSUE THREAD

**Issue by peros550** [jandelgado/jled#120]
Hi 

Would it be possible to return the pin to its previous state after Blink function finishes ?

Thanks,

**Comment by jandelgado** [comment]
You could do something like

```c++
#include <jled.h>

auto led = JLed(LED_BUILTIN).Blink(1000, 1000).Repeat(5);

void setup() {
}

void loop() {
  if (!led.Update()) {
    led.Off().Update();   // or whatever you want 
  }


}

```

`Update() `  only returns `true`  as long as the effect is still active.
