### ISSUE TITLE
Is there a way to use a single JLED to control a bicolor led? 

### ISSUE THREAD

**Issue by Rimbaldo** [jandelgado/jled#123]
How can I make a single RED/GREEN bicolor led to work with JLED but using the Yellow color? Both Red and Green lit, to show yellow effects?

Also, can I create an "Yellow" Object that sets the max brightness different for each color (RED and GREEN) , so I can tune the best "yellow" appearance?

Is there a way for this to be done?

Thanks!

**Comment by jandelgado** [comment]
Currently only single-color LEDs are supported.But you could create a `JLedSequence` with 2 `JLed` objects, one for red and for the green LED and control the LEDs in parallel together.
