### ISSUE TITLE
ESP8266: Watchdog Timer Reset when using v4.0.0-rc0 release

### ISSUE THREAD

**Issue by marrold** [jandelgado/jled#16]
Hi, I'm trying to use a basic example on a NodeMCU ESP8266 board, but I am getting Watchdog Timer Resets.

Error:

```
 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset
```

Code:

```
#include <Arduino.h>

#include <jled.h>

JLed led = JLed(LED_BUILTIN).On().DelayBefore(2000);

void setup() {
}

void loop() {
  led.Update();
}
```

Am I doing something wrong?

Thanks!

**Comment by jandelgado** [comment]
I can reproduce the problem and am working on a fix - thanks for the report.

**Comment by marrold** [comment]
Thanks 😃

**Comment by jandelgado** [comment]
I located the problem in the newly introduced placement new, which needs to use an aligned buffer on the ESP8266. I'll provide a fix tomorrow.

**Comment by marrold** [comment]
This is working perfectly, thanks
