### ISSUE TITLE
version is incorrect in library.properties

### ISSUE THREAD

**Issue by sslupsky** [jandelgado/jled#21]
This line is not compliant with the spec for library.properties version property:

https://github.com/jandelgado/jled/blob/6643a5f4122dbf3a284664564a98faecc0d85c65/library.properties#L2

It is throwing an "Invalid Version" error at compile time.

I think you need to remove the "v" at the beginning.

**Comment by jandelgado** [comment]
Strange - that seemed to be a new behaviour, but your are right, thats what the [spec ](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) states:

> version - version of the library. Version should be semver compliant. 1.2.0 is correct; 1.2 is accepted; r5, 003, 1.1c are invalid

Always had the "v" in front of the version before. I'll soon change it and release a new version.

**Comment by jandelgado** [comment]
I just released 4.1.1 does it work now?

**Comment by sslupsky** [comment]
That fixed it!  Thank you!

**Comment by sslupsky** [comment]
I think it might be an issue introduced in one of the recent IDE updates?  Not sure.  I found this reference:

https://forum.arduino.cc/index.php?topic=596113.0

Which referred to the spec:

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

Which refers to "semver".

**Comment by jandelgado** [comment]
Excellent - thanks for pointing out the problem
