### ISSUE TITLE
The sequence.ino example doesn't work on ESP32

### ISSUE THREAD

**Issue by iZhangHui** [jandelgado/jled#22]
It seems that just the last sequence effect work.

**Comment by jandelgado** [comment]
Hi, could you please describe a little bit more detailed the expected and observed behaviour?

The last "effect" in the [sequence](https://github.com/jandelgado/jled/blob/master/examples/sequence/sequence.ino) example is to turn the LED off (i.e. `Off()`). 

https://github.com/jandelgado/jled/blob/8701e212660f497e6b0cb21a8fb0a0f8c85e8e07/examples/sequence/sequence.ino#L10

Regarding your report, that would mean that the the whole demo would not show anything, correct?

**Comment by iZhangHui** [comment]
Yes, your describe is right, the whole demo would not show anything.
When I comment the codes of Line 11, 12, 13, the demo will fadeoff 3 times, and so forth.

**Comment by jandelgado** [comment]
Ok, will check this in a few days. Thanks for the report.

**Comment by jandelgado** [comment]
Good news: I've spotted the problem in the ESP32 HAL, in the pin-channel assignment. Will fix it coming weekend.

**Comment by jandelgado** [comment]
@iZhangHui release 4.1.2 should fix the problem - could you please retest?

**Comment by iZhangHui** [comment]
I will retest and give you feedback.

**Comment by iZhangHui** [comment]
Verified, It works.  :）

**Comment by jandelgado** [comment]
Excellent - thanks.
