### ISSUE TITLE
auto led = JLed(ledPin).Blink(1, 1000).Forever(); doesn't does not blink regularly.

### ISSUE THREAD

**Issue by avandalen** [jandelgado/jled#36]
What can you program well! I am overwhelmed with this library...
just:
auto led = JLed(ledPin).Blink(1, 1000).Forever(); doesn't does not blink regularly.
auto led = JLed(ledPin).Blink(2, 1000).Forever(); is okey

**Comment by jandelgado** [comment]
`Blink(1,1000)` means to turn the LED on for 1ms and to turn it off for 1000ms = 1 second afterwards. I did not test it, but I doubt that this 1ms "flash" will be visible to the human eye. 

What do you exactly expect?

**Comment by avandalen** [comment]
It is funny, Blink(1, 1000) is still visable, look what happens...
To save power, I use 2ms in my application.

**Comment by jandelgado** [comment]
So I was curious to see if there might be a bug or some unexpected behaviour. I connected a LED to an Arduino nano and checked with an Oscilloscope if output is as expected. Luckily it is:

* `Blink(1,1000)`
![grafik](https://user-images.githubusercontent.com/11670798/68995228-974b6b00-088b-11ea-8654-27ead85e7b7e.png)

* `Blink(2,1000)`
![grafik](https://user-images.githubusercontent.com/11670798/68995234-a3372d00-088b-11ea-99b8-00f2c9039a0e.png)

* Both effects have a period of 1000ms:
![grafik](https://user-images.githubusercontent.com/11670798/68995244-c366ec00-088b-11ea-98cd-886af2b087bb.png)

Everythin works as expected, I do not see an issue. Can we close the issue?
br Jan

**Comment by avandalen** [comment]
In my case the LED was not blinking regulary with 1ms (visually) , but I have not checked it with my oscilloscope, i will check that, you can close the isue
thank you very much
