### ISSUE TITLE
Is the Running Function implemented?

### ISSUE THREAD

**Issue by claytoncamilleri100** [jandelgado/jled#38]
I am trying to use this library for a project and the last thing I need is the IsRunning function. When I try to use it I get "Class JLed has no member named `isRunning`" Looking in the library jled.h file there is no mention of this function.

**Comment by jandelgado** [comment]
It is hopefully implemented ;) C++ is case sensitive. The method is called `IsRunning` and is defined here:

https://github.com/jandelgado/jled/blob/7219c3a0f0afaa39becdb3b7fc502c978e892dcf/src/jled_base.h#L345

It is also used in the unit test, e.g.
https://github.com/jandelgado/jled/blob/7219c3a0f0afaa39becdb3b7fc502c978e892dcf/test/test_jled.cpp#L248

**Comment by jandelgado** [comment]
Closed due to inactivity
