### ISSUE TITLE
Extend JLedSequence with and ability to suspend it (On/Off).

### ISSUE THREAD

**Issue by 3dluvr** [jandelgado/jled#48]
Hi,

After looking into the library code, I think I have an idea how a sequence could be suspended. This might be a quick fix, or a dirty hack, not sure - I just know I need it.

Two new methods would be created: **.Off()** and **.On()**:

.Off() would allocate a new private/protected array **leds_saved_**, and copy the sequence's **leds_** into **leds_saved_**. Then it would call **leds_[i].Off()** to turn them off. Finally, might have to call **Update()** once the iteration though LEDs is done?

.On() would copy the **leds_saved_** array back into **leds_**, and free **leds_saved_**. Might need to call **Reset()** once the copy is done, too?

Unfortunately, I don't have the savviness to do this myself as I'm not familiar with the library and my C++ skills aren't up to snafu either.

**Comment by jandelgado** [comment]
Working on it in #102
