### ISSUE TITLE
Compiler fails invalid conversion from int to PinName Nano Sense 33 BLE 

### ISSUE THREAD

**Issue by Naphier** [jandelgado/jled#53]
Nano Sense 33 BLE 

Compiler fails:
`invalid conversion from 'int' to 'jled::MbedHal::PinType {aka PinName}' [-fpermissive]`

Code: 
`auto led = JLed(13).Blink(1000,500).Forever();`
Also fails with `LED_BUILTIN`

**Comment by jandelgado** [comment]
Hi @Naphier,
which environment (e.g. Arduino IDE / PlatformIO) and settings (Board/Framework) did you use?

**Comment by jandelgado** [comment]
I installed the `Arduino nRF528x mbed Core ` into the Arduino IDE and can confirm that it does not compile. However, the following workaround (`#undef __MBED__`) does compile. Could you please try while I further investigate the issue:

```c++
#undef __MBED__
#include <jled.h>

auto led = JLed(13).Blink(1000,500).Forever();

void setup() {  
}

void loop() {
  led.Update();
}
```

**Comment by Naphier** [comment]
Thanks. Just got the Nano Sense 33 and prefer this library over others (so many juicy options). 
Using Arduino IDE 1.8.18  (don't think that matters)
and  Arduino Nano 33 BLE (nRF528x - MbedOS)
Your workaround allows it to work, but I worry undef'ing __MBED__ will cascade to other things.

**Comment by jandelgado** [comment]
Excellent - I'll provide a fix that does not make the `#undef` necessary. Thanks for testing

**Comment by jandelgado** [comment]
Please check #54 for a fixed version - does it work for you?

**Comment by Naphier** [comment]
Solid. Thanks for the quick turnaround. Apologies that I couldn't test it sooner for you.
