### ISSUE TITLE
ESP32 Non-linear period when set longer than 65000ms

### ISSUE THREAD

**Issue by Didgeridrew** [jandelgado/jled#55]
Caveat: I am a total noob, I'm sorry if I missed something that should be obvious.

I was trying to create a long (15min) fade up, and I was getting very strange fluctuations in the actual period vs the period setting.  Since it is hard to tell exactly how long a fade cycle takes due to led brightness perception, I used the user_func example and changed the period. Up to a period of 65000ms the actual period matches the setting, then it goes squirrelly:

66000 = 1 blink of the led
68000 = 3 sec
70000 = 6 sec
80000 = 15 sec
90000 = 25 sec
900000 = 47sec
1000000 = 17sec

**Comment by jandelgado** [comment]
The period is modelled as a 16 bit integer. Therefore the maximum period is 65535 ms. Every value you provide is effectively ANDed by 0xfffff so if you provide e.g. 68000 the actual period is 68000 & 0xffff = 2464 ms.

Hope that helps.

regards
Jan

**Comment by Didgeridrew** [comment]
Jan, thank you so much for your quick reply and all the work you've done to create this library. I was able to modify the pertinent parts to get it to work the way I need for my project.
