### ISSUE TITLE
Brightness Logic Inverted

### ISSUE THREAD

**Issue by ElectronicsBoi** [jandelgado/jled#59]
So i am using my esp32 wemos lolin32 board, for some reason the brightness logic is inverted. Set(255) cause LED to turn Off and Set( 0) causes LED to turn on. The Brightness scale is 255 to 0 , with 255 being the max and 0 being the lowest. The max brightness function also behaves a little erroneously when used with effects but correcting the brightness logic would solve this problem. The same is the case with effects(without adding max brightness) fade on becomes fade off and vice versa. I think it may be a problem that code isn't best suited for some/all of the esp32 boards?

**Comment by ElectronicsBoi** [comment]
I cant determine whether the breathe function looks fine or not, maybe because it involves both fade in and fade out, so it is difficult to determine which comes first. But one thing i did notice that it stays bright more than it stays dark. I don't know if it is the function's general behavior or due to the values being inverted in the waveform.

**Comment by jandelgado** [comment]
I‘m not sure of I understood what your exact Problem is. But for inverted Outputs as described by you, you should try to use LowActive()

https://github.com/jandelgado/jled#low-active-for-inverted-output

br Jan

**Comment by ElectronicsBoi** [comment]
Low active is just a fix for my board. I would appreciate it if the library is adapted somehow. Set(255) turns led off, fadein functions actually behaves as a fade off and fade off as a fade on. Max brightness cannot be used for some reason. I think if you have a lolin32 board, you should try your code on it. 

P.S The code works fine on my esp32 devkit board

**Comment by ElectronicsBoi** [comment]
Yep, that was the problem, my on-board led was pulled low.
