### ISSUE TITLE
ESP32 Unable to define channel

### ISSUE THREAD

**Issue by Johnymalina** [jandelgado/jled#62]
Hi,

i have problem with assign pins and channels using Esp32Hal(pin, chan). I get a message that Esp32Hal is not defined. I tried to include also esp32-hal.h library but without effect. Using only pin number works everythig fine but i would like to have more control of channels. I tried to explore what could cause this issue but the code is too complex for me. 

I tried also just copy paste example from readme and it doesnt work either. 

Thanks for your help.

**Comment by Johnymalina** [comment]
I have managed to find a solution adding jled:: before jled helped. Is this expected behaviour? Maybe update to readme is in order:
Final code that worked for me is:
`auto esp32Led = JLed(jled::Esp32Hal(2, 7)).Blink(1000, 1000).Forever();`

**Comment by jandelgado** [comment]
Yes, it's namespaced. I'll update the docs - thanks for the hint.

**Comment by jandelgado** [comment]
README.md updated on b0373f90474701d95b667ed6a645efd7765e0e85 (master)
