### ISSUE TITLE
[Question]: Looking for a function like myLed.isOn(), myLed.isOff()

### ISSUE THREAD

**Issue by OllisGit** [jandelgado/jled#7]
First: I like your lib very much! I appreciate your effort.

What is the best way to check if a led is currently on/off or (optional) get the brigthness value?

Thx
Olli

**Comment by jandelgado** [comment]
Currently there is no direct way to check the status of the LED. What is your concrete use-case for that feature?
regards
Jan

**Comment by OllisGit** [comment]
I am using different LEDs for indicating several events. 
The LEDController function is running on a seperate Thread/TaskHandle.
Each time a event occours in the main-thread a differnt LED is switched on (with/without animation). via LEDController.
At the moment I am "storing" the  event-information in a lot of fields in led controller. And these fields "pollute" my LEDController-Code ;-)

It would be great if i have the opportunity to ask leds which state they have. 
E.g. "emergency-event: if orange led is on, turn off, turn on red led"

BR
Olli

**Comment by jandelgado** [comment]
Currently you can check if an effect is running by looking at the return code of the Update() method. In the next release I'll also add a method to check if the effect is done or not (e.g. led.IsRunning())
Would that solve your problem?

**Comment by OllisGit** [comment]
Sounds good!
I think I can store the returned Update-Flag from each LED and provide my own status-methode (as a workaround, waiting for next release ;-).

Thx, in advance
Olli

**Comment by jandelgado** [comment]
The 4.0.0 release of JLed (see version in master branch) now has a IsRunning method:

bool JLed::IsRunning() const

indicating if the effect is still running.
