### ISSUE TITLE
how can i use to pca9685

### ISSUE THREAD

**Issue by K0rkunc** [jandelgado/jled#76]
how can i use to pca9685

**Comment by jandelgado** [comment]
Controlling LEDs using a PCA9685 is currently not supported by JLed. I'll put a task in the backlog and do some research in the next weeks. Basically a new HAL needs to be written, which communicates with the PCA9685 using I2C.

**Comment by K0rkunc** [comment]
hello i added pca9685 support to your library

I also added a 4095 gamma table for 12 bit pwm resolution.

I needed a ramp for 20 minutes or more, but I realized that the ramp that took that long does not work in your library, I couldn't fix it. Do you have a solution?

**Comment by jandelgado** [comment]
what exactly do you mean by "ramp fo 20 minutes or more"? You want a `FadeOn` with a period of 20 minutes?

**Comment by K0rkunc** [comment]
evet 20 min and 60 min
