### ISSUE TITLE
Reversed logic

### ISSUE THREAD

**Issue by arkypita** [jandelgado/jled#9]
First of all, great job!
I have a question: my LED is driven by a PNP transistor, so high level is off, low level is on.
Is there any way to reverse Jled logic?

**Comment by arkypita** [comment]
I read "Features: supports reversed polarity of LED" but not find any sample

**Comment by jandelgado** [comment]
Yes, it is supported. The method is called `LowActive()`. Example:

JLed led = JLed(LED_BUILTIN).Blink(500, 100).LowActive();

br
Jan

**Comment by arkypita** [comment]
thanks!
