### ISSUE TITLE
Question: How to pass to funtion

### ISSUE THREAD

**Issue by BernhardSchlegel** [jandelgado/jled#97]
Hey there,

I've created a JLed, I.e. using

```
auto my_led = JLed(GPIO_LED).LowActive().Off();
```

How do I pass that to a function

```
void fooFunction($WHAT_GOES_HERE$ led) { ... }
```

I've tried `jled::JLed::TJLed`, `jled::JLed`, `auto` ... nothing works. (I.e. resulting into `error: use of deleted function 'jled::JLed::JLed()'`)

Thanks!

**Comment by jandelgado** [comment]
The type is simply `JLed`, so you could for example pass a reference with something like (make sure to a recent JLed version):

```c++
#include <jled.h>

auto led = JLed(LED_BUILTIN).Blink(1000, 1000).Repeat(5);

void dosomething(JLed& led) {
    led.Stop();
}

void setup() {
}

void loop() {
  led.Update();
  dosomething(led);
}
```
